config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :entries
  resources :prints, only: [:index] do
    collection do
      get :trigger
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'entries#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true

  scope :active, -> { where(active: true) }
end

app/models/entry.rb
class Entry < ApplicationRecord

  validates :amount, :activity_date, :expense, presence: true

  belongs_to :category

  scope :for_today, -> (date = Date.today) { includes(:category).where( activity_date: date ) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    @categories = Category.active
  end

  def show;end

  def new
    @category = Category.new
  end

  def edit;end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @category.update(active: false)
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
    end
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  def index
    @entries = Entry.all
  end

  def show;end

  def new
    @entry = Entry.new
  end

  def edit;end

  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
    end
  end

  private
    def set_entry
      @entry = Entry.includes(:category).find(params[:id])
    end

    def entry_params
      params.require(:entry).
        permit(:activity_date, :amount, :notes, :category_id, :expense)
    end
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController

  def index
    @entries = Entry.for_today
  end

  def trigger
    SummaryJob.perform_now
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true, class: 'ui form') do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', {class: 'ui blue right floated button'} %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="ui raised very padded text container segment">
  <h4 class="ui dividing header">Edit Category Information</h4>

  <%= render 'form', category: @category %>

  <div class="ui buttons">
    <%= link_to 'Show', @category, class: 'ui black button' %>
    <div class="or"></div>
    <%= link_to 'Back', categories_path, class: 'ui positive button' %>
  </div>
</div>

app/views/categories/index.html.erb
<div class="ui container">
  <p id="notice"><%= notice %></p>

  <h3>Categories</h3>

  <table id='categories'>
    <thead>
      <tr>
        <th>Name</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= link_to category.name, category %></td>
          <td class='centered'>
            <%= link_to 'Edit', edit_category_path(category) %> |
            <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $("#categories").dataTable({
      "oLanguage": {
        "sSearch": "Filter Data"
      },
      columnDefs: [
        {
          orderable: false,
          targets: 1
        }
      ]
    });
  });
</script>

app/views/categories/new.html.erb
<div class="ui raised very padded text container segment">
  <h4 class="ui dividing header">New Category Information</h4>

  <%= render 'form', category: @category %>

  <%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<div class="ui raised very padded text container segment">
  <p id="notice"><%= notice %></p>

  <h3>Category</h3>
  <p>
    <strong>Name:</strong>
    <%= @category.name %>
  </p>

  <div class="ui buttons">
    <%= link_to 'Edit', edit_category_path(@category), class: 'ui button' %>
    <div class="or"></div>
    <%= link_to 'Back', categories_path, class: 'ui positive button' %>
  </div>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true, class: 'ui form') do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="two fields">
    <div class="field">
      <div class="ui radio checkbox">
        <%= form.radio_button :expense, 1 %>
        <%= form.label :expense %>
      </div>
    </div>
    <div class="field">
      <div class="ui radio checkbox">
        <%= form.radio_button :expense, 0 %>
        <%= form.label :income %>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.select(:category_id, Category.active.collect {|d| [d.name, d.id]}, {:include_blank => "Select"}) %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: :any %>
  </div>

  <div class="field">
    <%= form.label :activity_date %>
    <%= form.date_field :activity_date %>
  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_field :notes %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', {class: 'ui blue right floated button'} %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<div class="ui raised very padded text container segment">
  <h4 class="ui dividing header">Edit Entry Information</h4>

  <%= render 'form', entry: @entry %>

  <div class="ui buttons">
    <%= link_to 'Show', @entry, class: 'ui black button' %>
    <div class="or"></div>
    <%= link_to 'Back', entries_path, class: 'ui positive button' %>
  </div>
</div>

app/views/entries/index.html.erb
<div class="ui container">
  <p id="notice"><%= notice %></p>

  <h3>Expense / Income</h3>

  <div class='ui segment right floated'>
    <span>Minimum Date:<input name="min" id="min" type="date"></span>
    <span>Maximum Date:<input name="max" id="max" type="date"></span>
  </div>
  <table id='entries'>
    <thead>
      <tr>
        <th>Type</th>
        <th>Category</th>
        <th>Amount</th>
        <th>Activity Date</th>
        <th>Notes</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.expense == 1 ? 'Expense' : 'Income' %></td>
        <td><%= entry.category.name %></td>
        <td><%= entry.amount %></td>
        <td><%= entry.activity_date %></td>
        <td><%= entry.notes %></td>
        <td class="centered">
          <%= link_to 'Edit', edit_entry_path(entry) %> |
          <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    var minDateFilter = "";
    var maxDateFilter = "";

    var table = $("#entries").dataTable({
      "oLanguage": {
        "sSearch": "Filter Data"
      },
      columnDefs: [
        {
          orderable: false,
          targets: 5
        }
      ]
    });

    $.fn.dataTableExt.afnFiltering.push(
    function(oSettings, aData, iDataIndex) {
      if (typeof aData._date == 'undefined') {
        aData._date = new Date(aData[3]).getTime();
      }

      if (minDateFilter && !isNaN(minDateFilter)) {
        if (aData._date < minDateFilter) {
          return false;
        }
      }

      if (maxDateFilter && !isNaN(maxDateFilter)) {
        if (aData._date > maxDateFilter) {
          return false;
        }
      }

      return true;
    });

    $('#min').change(function() {
      minDateFilter = new Date(this.value).getTime();
      table.fnDraw();
    });

    $('#max').change(function() {
      maxDateFilter = new Date(this.value).getTime();
      table.fnDraw();
    });
  });
</script>

app/views/entries/new.html.erb
<div class="ui raised very padded text container segment">
  <h4 class="ui dividing header">New Entry Information</h4>

  <%= render 'form', entry: @entry %>

  <%= link_to 'Back', entries_path %>
</div>

app/views/entries/show.html.erb
<div class="ui raised very padded text container segment">
  <p id="notice"><%= notice %></p>

  <h3><%= @entry.expense == 1 ? 'Expense' : 'Income' %> Entry</h3>
  <p>
    <strong>Category:</strong>
    <%= @entry.category.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= @entry.amount %>
  </p>

  <p>
    <strong>Activity Date:</strong>
    <%= @entry.activity_date .strftime('%B %d, %Y')%>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= @entry.notes %>
  </p>

  <div class="ui buttons">
    <%= link_to 'Edit', edit_entry_path(@entry), class: 'ui button' %>
    <div class="or"></div>
    <%= link_to 'Back', entries_path, class: 'ui positive button' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css"/>

    <script type="text/javascript" src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>



  </head>

  <body>
    <div class="ui menu">
      <%= link_to 'Entries', root_path, class: 'item' %>
      <%= link_to 'Categories', categories_path, class: 'item' %>
      <%= link_to 'Todays Entries', prints_path, class: 'item' %>
      <span class='item right f ui block header'>
        Budget Tracker
      </span>
    </div>
    <div class="ui container segment">
      <div id='additions' class="">
        <%= link_to new_entry_path, class: 'ui right button positive' do %>
          <i class="calendar alternate icon"></i>New Entry
        <% end %>
        <%= link_to new_category_path, class: 'ui right floated button positive' do %>
          <i class="clipboard outline icon"></i>New Category
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/prints/index.html.erb
<div class='ui container'>
  <h3>Entries for today (<%= Date.today.strftime('%B %d, %Y') %>)</h3>
  <table class='ui celled table'>
    <thead>
      <th>Type</th>
      <th>Category</th>
      <th>Amount</th>
      <th>Activity Date</th>
      <th>Notes</th>
    </thead>
    <tbody>
      <% @entries.each do |entry| %>
        <tr>
          <td><%= entry.expense == 1 ? 'Expense' : 'Income' %></td>
          <td><%= entry.category.name %></td>
          <td><%= entry.amount %></td>
          <td><%= entry.activity_date %></td>
          <td><%= entry.notes %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= link_to 'Print', '#', class: 'ui right floated button positive', id: 'print' %>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    $('#print').on('click', function(e) {
      $.ajax({
        url: '/prints/trigger'
      }).
      done(function(resp) {
        alert('Printed in the logs');
      });
      e.preventDefault();
    });
  });
</script>